site_name: TRamWAy doc v0.1

repo_url: https://github.com/DecBayComp/tramway-tour

nav:
  - Introduction: index.md
  - Tracking: tracking.md
  - Segmentation: segmentation.md
  - Inference: inference.md
  - More:
      - ROI: roi.md

theme:
  name: material
  highlightjs: false
  features:
    - navigation.tabs
    - toc.integrate

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.keys
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/material.css
  - stylesheets/pygments.css
